---
- name: Configure CI Server
  hosts: all
  vars:
    jenkins_plugins:
      - github
      - mask-passwords
      - ssh
      - scm-sync-configuration
      - blueocean
      - postbuild-task
  become: yes
  roles:
    - docker
    - jenkins