- name: set ownership for jenkins_home folder
  file:
    path: /vagrant/jenkins_home
    owner: 1000
    group: 1000
    recurse: yes
  become: yes

- name: jenkins container is present
  docker_container:
    name: mcit_jenkins
    image: jenkins/jenkins:lts
    state: started
    pull: yes
    restart_policy: always
    network_mode: host
    exposed_ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /vagrant/jenkins_home:/var/jenkins_home
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  become: yes
